//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_TryIt.XML_Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML_Services.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validation", ReplyAction="http://tempuri.org/IService1/ValidationResponse")]
        bool Validation(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Validation", ReplyAction="http://tempuri.org/IService1/ValidationResponse")]
        System.Threading.Tasks.Task<bool> ValidationAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XMLPathSearch", ReplyAction="http://tempuri.org/IService1/XMLPathSearchResponse")]
        string XMLPathSearch(string url, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/XMLPathSearch", ReplyAction="http://tempuri.org/IService1/XMLPathSearchResponse")]
        System.Threading.Tasks.Task<string> XMLPathSearchAsync(string url, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : XML_TryIt.XML_Services.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<XML_TryIt.XML_Services.IService1>, XML_TryIt.XML_Services.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validation(string url) {
            return base.Channel.Validation(url);
        }
        
        public System.Threading.Tasks.Task<bool> ValidationAsync(string url) {
            return base.Channel.ValidationAsync(url);
        }
        
        public string XMLPathSearch(string url, string path) {
            return base.Channel.XMLPathSearch(url, path);
        }
        
        public System.Threading.Tasks.Task<string> XMLPathSearchAsync(string url, string path) {
            return base.Channel.XMLPathSearchAsync(url, path);
        }
    }
}
